// ==UserScript==
// @name        Eyny
// @namespace   yanagiragi
// @include     http://*.eyny.com/index.php
// @require     https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js
// @version     1.7
// @grant       none
// @description Simple Enhanced Feature of eyny.com
// ==/UserScript==

// Purpose : with entering "eyny.com", you will grant
// 1. new url with www****.eyny.com, to avoid imgur.com blocking www**.eyny.com
// 2. Already agreeed you are over 18 years old :)
// 3. No longer access homepage twice if you're trying to access some forums

// Don't touch this, this is my development flags
const debug = false

const exclude = ['22']
const fourmIDStatic = {
    "時事": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1724",
    "生活": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=68",
    "投票": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3181",
    "電影": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=205",
    "籃球": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=365",
    "星座": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=56",
    "有趣": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1760",
    "食戟": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4138",
    "吹水聊天室": "http://www06.eyny.com/forum-27-1.html",
    "歷史回憶區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1831",
    "網友交友區": "http://www06.eyny.com/forum-88-1.html",
    "靈異鬼故事": "http://www06.eyny.com/forum-30-1.html",
    "UFO及超自然力量": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=491",
    "血腥嘔心區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1830",
    "生活百科及冷知識": "http://www06.eyny.com/forum-68-1.html",
    "健康資訊": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=411",
    "IQ題猜迷語": "http://www06.eyny.com/forum-102-1.html",
    "趣味笑話區": "http://www06.eyny.com/forum-54-1.html",
    "限制級笑話區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=296",
    "性教育專區": "http://www06.eyny.com/forum-210-1.html",
    "布袋戲討論": "http://www06.eyny.com/forum-1609-1.html",
    "布袋戲貼圖": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1611",
    "布袋戲下載": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1610",
    "詩詞文學創作區&amp;綜合區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1792",
    "知識問與答": "http://www06.eyny.com/forum-1723-1.html",
    "當兵生活趣談": "http://www06.eyny.com/forum-1758-1.html",
    "海外生活": "http://www06.eyny.com/forum-1763-1.html",
    "活動中心": "http://www06.eyny.com/forum-2037-1.html",
    "投票中心": "http://www06.eyny.com/forum-3181-1.html",
    "其他興趣討論": "http://www06.eyny.com/forum-1721-1.html",
    "模型和玩具": "http://www06.eyny.com/forum-152-1.html",
    "魔術討論區": "http://www06.eyny.com/forum-244-1.html",
    "攝影交流": "http://www06.eyny.com/forum-383-1.html",
    "卡牌交流": "http://www06.eyny.com/forum-381-1.html",
    "遊戲王": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2006",
    "CARDDAS TCG交流區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=493",
    "武士道TCG交流區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=494",
    "魔獸世界": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2021",
    "MTG": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2022",
    "棋藝交流": "http://www06.eyny.com/forum-382-1.html",
    "中國象棋": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=495",
    "國際象棋": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=496",
    "圍棋": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=497",
    "釣魚交流": "http://www06.eyny.com/forum-455-1.html",
    "天文地理交流": "http://www06.eyny.com/forum-442-1.html",
    "War Games 交流": "http://www06.eyny.com/forum-456-1.html",
    "紙藝小築/摺紙手工": "http://www06.eyny.com/forum-502-1.html",
    "風水玄學及掌相命理": "http://www06.eyny.com/forum-468-1.html",
    "園藝交流": "http://www06.eyny.com/forum-499-1.html",
    "巴士迷專區": "http://www06.eyny.com/forum-500-1.html",
    "舞蹈交流": "http://www06.eyny.com/forum-498-1.html",
    "機車交流": "http://www06.eyny.com/forum-501-1.html",
    "機車貼圖": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=507",
    "藝術及繪畫": "http://www06.eyny.com/forum-504-1.html",
    "汽車交流": "http://www06.eyny.com/forum-505-1.html",
    "汽車貼圖": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=49",
    "會員寫作專欄": "http://www06.eyny.com/forum-470-1.html",
    "大學生活交流": "http://www06.eyny.com/forum-363-1.html",
    "中學生活交流": "http://www06.eyny.com/forum-162-1.html",
    "小學生活交流": "http://www06.eyny.com/forum-364-1.html",
    "各類考試討論": "http://www06.eyny.com/forum-362-1.html",
    "中國文學": "http://www06.eyny.com/forum-408-1.html",
    "科學討論": "http://www06.eyny.com/forum-407-1.html",
    "哲學討論": "http://www06.eyny.com/forum-358-1.html",
    "心靈小品 (短篇)": "http://www06.eyny.com/forum-89-1.html",
    "好書推介及閱讀感想": "http://www06.eyny.com/forum-409-1.html",
    "歷史討論": "http://www06.eyny.com/forum-149-1.html",
    "宗教討論": "http://www06.eyny.com/forum-221-1.html",
    "藝術交流": "http://www06.eyny.com/forum-508-1.html",
    "日本文化": "http://www06.eyny.com/forum-522-1.html",
    "英語學習坊": "http://www06.eyny.com/forum-1730-1.html",
    "留學遊學交流": "http://www06.eyny.com/forum-1757-1.html",
    "神話傳說": "http://www06.eyny.com/forum-1759-1.html",
    "旅遊風光相簿": "http://www06.eyny.com/forum-202-1.html",
    "旅遊經驗交流": "http://www06.eyny.com/forum-512-1.html",
    "世界遊樂園討論區": "http://www06.eyny.com/forum-419-1.html",
    "中國/澳門/台灣": "http://www06.eyny.com/forum-513-1.html",
    "日本/韓國": "http://www06.eyny.com/forum-514-1.html",
    "歐洲/美洲/非洲/其他": "http://www06.eyny.com/forum-515-1.html",
    "東南亞/澳洲/紐西蘭": "http://www06.eyny.com/forum-516-1.html",
    "美味食譜": "http://www06.eyny.com/forum-191-1.html",
    "食店及飲食討論": "http://www06.eyny.com/forum-517-1.html",
    "健康飲食": "http://www06.eyny.com/forum-518-1.html",
    "廚藝烹飪": "http://www06.eyny.com/forum-519-1.html",
    "世界美食討論": "http://www06.eyny.com/forum-1729-1.html",
    "零食討論": "http://www06.eyny.com/forum-1728-1.html",
    "品茶茶藝": "http://www06.eyny.com/forum-1727-1.html",
    "咖啡": "http://www06.eyny.com/forum-1726-1.html",
    "紅酒白酒及其他酒類": "http://www06.eyny.com/forum-1725-1.html",
    "婚姻大事": "http://www06.eyny.com/forum-509-1.html",
    "家居佈置": "http://www06.eyny.com/forum-510-1.html",
    "置業租屋": "http://www06.eyny.com/forum-511-1.html",
    "育兒父母區": "http://www06.eyny.com/forum-427-1.html",
    "寶貝BB貼圖": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1756",
    "家庭生活": "http://www06.eyny.com/forum-1717-1.html",
    "家事傾訴": "http://www06.eyny.com/forum-1718-1.html",
    "電玩單機遊戲情報討論": "http://www06.eyny.com/forum-209-1.html",
    "minecraft(當個創世神)": "http://www06.eyny.com/forum-3336-1.html",
    "戰慄時空之絕對武力(CS)": "http://www06.eyny.com/forum-86-1.html",
    "CS相關資源分享區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1809",
    "榮耀戰魂": "http://www06.eyny.com/forum-4291-1.html",
    "NEKOPARA": "http://www06.eyny.com/forum-4292-1.html",
    "看門狗 Watch Dogs": "http://www06.eyny.com/forum-4202-1.html",
    "湯姆克蘭西：全境封鎖": "http://www06.eyny.com/forum-4095-1.html",
    "上古卷軸 系列(The Elder Scrolls)": "http://www06.eyny.com/forum-3279-1.html",
    "東方project": "http://www06.eyny.com/forum-1823-1.html",
    "H-game討論區": "http://www06.eyny.com/forum-1946-1.html",
    "AVG成人遊戲": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4041",
    "H-game回憶錄": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4040",
    "戀姬系列版": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1877",
    "Muv-Luv": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4043",
    "大富翁遊戲系列": "http://www06.eyny.com/forum-2018-1.html",
    "超次元戰記●戰機少女": "http://www06.eyny.com/forum-4042-1.html",
    "RPG製作大師": "http://www06.eyny.com/forum-4044-1.html",
    "策略模擬遊戲": "http://www06.eyny.com/forum-1939-1.html",
    "模擬市民大會廳": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1714",
    "世紀帝國系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=136",
    "SPORE": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1712",
    "三國志系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1967",
    "英雄連隊系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1920",
    "信長之野望系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1968",
    "紅色警戒系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1785",
    "星海爭霸": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1912",
    "大(萌)戰略 系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2015",
    "工人物語": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2014",
    "模擬城市": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2013",
    "幕府將軍": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3318",
    "輕Gal Game": "http://www06.eyny.com/forum-1938-1.html",
    "奈須系列(Type Moon)": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1881",
    "Key社遊戲": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2017",
    "5pb.遊戲系列專區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4096",
    "sprite&amp;fairys系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1882",
    "秋之回憶": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1981",
    "射擊競技遊戲": "http://www06.eyny.com/forum-1940-1.html",
    "惡靈勢力（Left 4 Dead）": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1784",
    "榮譽勳章系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1900",
    "Call of Duty 決勝時刻系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1962",
    "Battlefield 戰地風雲系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1960",
    "CRYSIS 末日之戰系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1959",
    "角色扮演遊戲": "http://www06.eyny.com/forum-1941-1.html",
    "仙劍奇俠傳系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1943",
    "風色幻想系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1944",
    "軒轅劍系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1965",
    "霹靂 系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1713",
    "英雄傳說系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1715",
    "伊蘇系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1966",
    "幻想三國誌系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1711",
    "古劍奇譚": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1984",
    "異塵餘生": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3328",
    "運動/競速遊戲": "http://www06.eyny.com/forum-1942-1.html",
    "EA SPORT": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1915",
    "極速快感系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1969",
    "NBA 2K series系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3455",
    "格鬥技術遊戲": "http://www06.eyny.com/forum-1987-1.html",
    "格鬥天王/拳皇": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1988",
    "冒險/動作遊戲": "http://www06.eyny.com/forum-2008-1.html",
    "俠盜獵車手": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1986",
    "刺客教條": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2010",
    "騎馬與砍殺": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3335",
    "蒼翼默示錄BLAZBLUE": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3333",
    "音速小子": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1985",
    "原型兵器（Prototype）": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1824",
    "魔獸爭霸系列": "http://www06.eyny.com/forum-273-1.html",
    "真三國無雙討論區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=324",
    "信長之野望討論區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=323",
    "Dota系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1963",
    "地圖編輯研究": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=422",
    "音樂節奏遊戲": "http://www06.eyny.com/forum-2011-1.html",
    "osu!": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1945",
    "StepMania": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3456",
    "太鼓之達人": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4045",
    "PC GAME 歷史回憶區": "http://www06.eyny.com/forum-2007-1.html",
    "電腦單機遊戲相關討論": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=384",
    "撕裂重罪hinokakera": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1989",
    "質感賽車": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3331",
    "07th Expansion系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2016",
    "美國陸軍系列（America's Army）": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1961",
    "黑暗領域": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3322",
    "永遠的毀滅公爵": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3324",
    "絕命異次元": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1990",
    "重裝武力": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3323",
    "魔法門之英雄無敵": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3319",
    "海商王": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3320",
    "冰與火之歌": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3321",
    "神鬼寓言": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3337",
    "末日危城": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3330",
    "質量效應": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3327",
    "大地王國": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3329",
    "東京山手BOYS": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2009",
    "波斯王子": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3334",
    "死亡之島": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3332",
    "電視遊樂器相關討論": "http://www06.eyny.com/forum-387-1.html",
    "任天堂 Switch": "http://www06.eyny.com/forum-4290-1.html",
    "Wii U 遊戲討論": "http://www06.eyny.com/forum-1701-1.html",
    "Wii遊戲及軟件分享": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1947",
    "Xbox 360 遊戲討論": "http://www06.eyny.com/forum-1702-1.html",
    "PS4 / PlayStation4": "http://www06.eyny.com/forum-388-1.html",
    "PS 遊戲及軟件分享": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=533",
    "PSV/ PlayStation Vita": "http://www06.eyny.com/forum-4135-1.html",
    "PSP / PlayStation Portable": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=385",
    "PSP 遊戲及軟件分享": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=534",
    "NDS / Nintendo DS": "http://www06.eyny.com/forum-386-1.html",
    "NDS 遊戲級軟件分享": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=535",
    "iPod / iPhone 綜合遊戲": "http://www06.eyny.com/forum-1950-1.html",
    "ARPG無雙系列": "http://www06.eyny.com/forum-1973-1.html",
    "真。三國無雙系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1704",
    "戰國 BASARA 系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1948",
    "戰國無雙系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1975",
    "無雙OROCHI系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1976",
    "鋼彈無雙系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1974",
    "俠盜獵車手(GTA)": "http://www06.eyny.com/forum-3915-1.html",
    "惡靈古堡系列": "http://www06.eyny.com/forum-1971-1.html",
    "神奇寶貝": "http://www06.eyny.com/forum-1709-1.html",
    "魔物獵人(M.H.)": "http://www06.eyny.com/forum-1703-1.html",
    "惡魔獵人": "http://www06.eyny.com/forum-1707-1.html",
    "時空幻境 系列": "http://www06.eyny.com/forum-1705-1.html",
    "遊戲王系列": "http://www06.eyny.com/forum-1993-1.html",
    "TV GAME 歷史回憶區": "http://www06.eyny.com/forum-3916-1.html",
    "太空戰士Final Fantasy": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1706",
    "快打旋風 系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1810",
    "七龍珠系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1992",
    "變形金剛": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1825",
    "勇者鬥惡龍系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1878",
    "NBA 2K series": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1893",
    "但丁的地獄之旅": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1901",
    "戰場女武神": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1995",
    "鋼彈系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1972",
    "三國志大戰": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1991",
    "超級機器人大戰 系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1708",
    "戰鼓PATAPON": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2019",
    "牧場物語": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2020",
    "街機遊戲討論": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=188",
    "掌機遊戲討論": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1949",
    "蘿球社": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2024",
    "閃電十一人": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1994",
    "英雄聯盟League of Legends": "http://www06.eyny.com/forum-1970-1.html",
    "暴雪英霸": "http://www06.eyny.com/forum-3887-1.html",
    "暗黑破壞神3：奪魂之鐮": "http://www06.eyny.com/forum-1710-1.html",
    "黑色沙漠 BLACK DESERT": "http://www06.eyny.com/forum-4259-1.html",
    "救世主之樹 Tree of Savior": "http://www06.eyny.com/forum-3969-1.html",
    "鬥陣特攻 Overwatch": "http://www06.eyny.com/forum-4128-1.html",
    "DMM綜合遊戲": "http://www06.eyny.com/forum-3311-1.html",
    "艦隊 Collection": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3698",
    "成人向遊戲專區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3971",
    "新楓之谷 Online": "http://www06.eyny.com/forum-1692-1.html",
    "流亡黯道 Path of Exile": "http://www06.eyny.com/forum-3503-1.html",
    "A.V.A 戰地之王 Revo": "http://www06.eyny.com/forum-1999-1.html",
    "天堂 Lineage系列": "http://www06.eyny.com/forum-113-1.html",
    "天堂貼圖": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1671",
    "戰艦世界World of Warships": "http://www06.eyny.com/forum-3908-1.html",
    "CS Online(絕對武力)": "http://www06.eyny.com/forum-1786-1.html",
    "艾爾之光": "http://www06.eyny.com/forum-1905-1.html",
    "爐石戰記：魔獸英雄傳": "http://www06.eyny.com/forum-3702-1.html",
    "仙境傳說RO系列": "http://www06.eyny.com/forum-31-1.html",
    "魔獸世界 WOW": "http://www06.eyny.com/forum-294-1.html",
    "戰車世界 World of Tanks": "http://www06.eyny.com/forum-3573-1.html",
    "劍靈Blade &amp; Soul": "http://www06.eyny.com/forum-3304-1.html",
    "新瑪奇英雄傳": "http://www06.eyny.com/forum-3306-1.html",
    "全民打棒球 2": "http://www06.eyny.com/forum-1633-1.html",
    "球隊資料專區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2025",
    "Pixiv角色創作專區": "http://www06.eyny.com/forum-3505-1.html",
    "艦隊提督鎮守府創作區": "http://www06.eyny.com/forum-3909-1.html",
    "角色扮演類〈MMORPG〉": "http://www06.eyny.com/forum-3910-1.html",
    "誅仙 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1693",
    "武林群俠傳 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1694",
    "精靈樂章 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1782",
    "希望戀曲Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1922",
    "LUNA系列 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1778",
    "風色幻想IF online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1883",
    "拉普拉斯的神子": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4052",
    "AION 永恆紀元": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1827",
    "聖境傳說Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1996",
    "晴空物語 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2028",
    "狩龍戰紀": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3742",
    "星界神話": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3888",
    "夢幻之星2 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3701",
    "石器時代": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2032",
    "RF Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1916",
    "天子傳奇 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1951",
    "參天律": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3572",
    "夢幻龍族傳說": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1818",
    "仙劍online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1821",
    "吞食天地 3 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3278",
    "神魔Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1997",
    "新龍之谷 Dragon Nest": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1979",
    "三國群英傳Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1886",
    "SF Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1829",
    "魔物獵人Frontier G": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1897",
    "名將列傳": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3305",
    "魔力寶貝": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1820",
    "新瑪奇 Mabinogi": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=257",
    "Unlight": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3310",
    "劍俠情緣3 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3282",
    "手機/平板遊戲情報特搜": "http://www06.eyny.com/forum-3889-1.html",
    "網路遊戲情報討論區": "http://www06.eyny.com/forum-139-1.html",
    "神魔之塔": "http://www06.eyny.com/forum-3577-1.html",
    "戰姬絕唱シンフォギア": "http://www06.eyny.com/forum-4338-1.html",
    "從零開始的魔法書": "http://www06.eyny.com/forum-4314-1.html",
    "闇影詩章(Shadowverse)": "http://www06.eyny.com/forum-4315-1.html",
    "龍族拼圖 Puzzle &amp; Dragons": "http://www06.eyny.com/forum-3578-1.html",
    "Pokemon GO": "http://www06.eyny.com/forum-4156-1.html",
    "白貓Project": "http://www06.eyny.com/forum-3818-1.html",
    "碧藍幻想": "http://www06.eyny.com/forum-4293-1.html",
    "幻想神域(手遊)": "http://www06.eyny.com/forum-3575-1.html",
    "偶像大師灰姑娘女孩": "http://www06.eyny.com/forum-4203-1.html",
    "刀塔傳奇": "http://www06.eyny.com/forum-3776-1.html",
    "陰陽師 Onmyoji": "http://www06.eyny.com/forum-4261-1.html",
    "少女前線": "http://www06.eyny.com/forum-4262-1.html",
    "Garena 傳說對決": "http://www06.eyny.com/forum-4223-1.html",
    "召喚圖板 Summons Board": "http://www06.eyny.com/forum-4098-1.html",
    "怪物彈珠": "http://www06.eyny.com/forum-3703-1.html",
    "克魯賽德戰記 Crusaders Quest": "http://www06.eyny.com/forum-3822-1.html",
    "鎖鏈戰記 CHAIN CHRONICLE": "http://www06.eyny.com/forum-3777-1.html",
    "Line遊戲系列討論版": "http://www06.eyny.com/forum-3705-1.html",
    "部落衝突Clash of Clans": "http://www06.eyny.com/forum-3855-1.html",
    "部落衝突：皇室戰爭": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4129",
    "Fate/Grand Order": "http://www06.eyny.com/forum-1954-1.html",
    "日系手遊討論": "http://www06.eyny.com/forum-3911-1.html",
    "七騎士": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4097",
    "神聖之門Divine Gate": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3309",
    "Crash Fever": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4054",
    "國產手遊討論": "http://www06.eyny.com/forum-3316-1.html",
    "知識王 LIVE": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3852",
    "雷霆戰機": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3778",
    "移動冒險": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3853",
    "波可龍迷宮": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3821",
    "其他手遊討論": "http://www06.eyny.com/forum-3317-1.html",
    "百萬亞瑟王": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3576",
    "Love Live! 學園偶像祭": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3704",
    "列王的紛爭 Clash of Kings": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3854",
    "口袋楓之谷": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3935",
    "問答RPG魔法使與黑貓維茲": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3819",
    "梅露可物語 癒術士與鈴之旋律": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3781",
    "勇者前線 Brave Frontier": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3314",
    "公主踢騎士": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3367",
    "魔靈召喚": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3820",
    "DQMSL 勇者鬥惡龍 怪物仙境": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3313",
    "劍與魔法王國 遠古的女神": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3970",
    "時空之門": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4053",
    "動畫(アニメ)改編討論": "http://www06.eyny.com/forum-1880-1.html",
    "魔法科高校劣等生系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3779",
    "刀劍神域系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3780",
    "私服討論區": "http://www06.eyny.com/forum-1631-1.html",
    "線上遊戲歷史回憶區": "http://www06.eyny.com/forum-2027-1.html",
    "風火之旅": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1698",
    "真‧三國無雙 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1699",
    "極速快車手 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1700",
    "希望 Online (New)": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1675",
    "81keys": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1781",
    "生死格鬥 Online（DOA Online）": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1828",
    "OGame銀河帝國": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1955",
    "百變恰吉": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1980",
    "Web 戀姫†夢想": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3389",
    "蒼天 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1695",
    "光明戰記（Holic2）": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1779",
    "吞食天地 2 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1780",
    "星空幻想 Online﹝Tartaros﹞": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1896",
    "彩虹島 Online（LaTale）": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1811",
    "女神 Online（NS Online）": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1812",
    "王國騎士團 Kingdom Knights": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3506",
    "萬王之王 3": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1783",
    "戰鎚 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1819",
    "飄流幻境": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1953",
    "迷你格鬥Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2000",
    "英雄島": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1921",
    "尬舞 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1958",
    "網頁遊戲討論": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1918",
    "Free Style": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1957",
    "末日禁區 AD Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2034",
    "TERA": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3303",
    "少女兵器 Web": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3312",
    "聖鬥士星矢 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3574",
    "跑跑卡丁車": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1632",
    "SAO 突襲 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1956",
    "幻月之歌 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2031",
    "達克布拉德（Dark Blood）": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3281",
    "IRIS瞳光 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1977",
    "信喵之野望": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3307",
    "幸福五角Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1923",
    "伊達傳說 EDDA Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3280",
    "永恆星語Web": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3426",
    "鬼武者魂": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3427",
    "路尼亞戰記": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1787",
    "Heva Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1978",
    "百年之戰": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3428",
    "新仙劍": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3699",
    "空中殺陣 ACE Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1788",
    "臥龍吟": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3308",
    "戰場女武神 DUEL": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3429",
    "埃米爾物語(ECO系列)": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1696",
    "AIKA": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1826",
    "烈日風暴Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1924",
    "百萬人的三國志 Special": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3507",
    "Q群仙傳Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1998",
    "狩神伝": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2033",
    "綜合網路遊戲討論區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1691",
    "幻想戰記(F.E.Zero)": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1697",
    "SD 鋼彈 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1822",
    "萌谷帝國 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2030",
    "Prius 守護之星 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1902",
    "未來啟示錄（SP1）": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1884",
    "七龍珠 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2029",
    "神諭之戰（Runes of Magic）": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1895",
    "劍俠世界": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1952",
    "神鬼奇兵 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1894",
    "火鳳三國 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1904",
    "裂痕RIFT": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3424",
    "龍Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1914",
    "Guild Wars 2": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3366",
    "嗜血 DNA Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1917",
    "DNF（Dungeon &amp; Fighter）": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3519",
    "中華英雄 Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1885",
    "劍狐傳奇": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1903",
    "超魔導大戰Online": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3504",
    "塔羅及占卜": "http://www06.eyny.com/forum-308-1.html",
    "星座心理區": "http://www06.eyny.com/forum-56-1.html",
    "愛情討論區": "http://www06.eyny.com/forum-42-1.html",
    "心情日記區": "http://www06.eyny.com/forum-40-1.html",
    "夢想與理想": "http://www06.eyny.com/forum-304-1.html",
    "小小祈願池": "http://www06.eyny.com/forum-418-1.html",
    "寵物新資訊": "http://www06.eyny.com/forum-1745-1.html",
    "其他寵物討論": "http://www06.eyny.com/forum-506-1.html",
    "狗狗": "http://www06.eyny.com/forum-1740-1.html",
    "貓貓": "http://www06.eyny.com/forum-1741-1.html",
    "爬蟲兩棲": "http://www06.eyny.com/forum-1744-1.html",
    "鼠類/兔類/龍貓類等": "http://www06.eyny.com/forum-1743-1.html",
    "雀鳥": "http://www06.eyny.com/forum-1742-1.html",
    "水族養魚樂": "http://www06.eyny.com/forum-503-1.html",
    "寵物貼圖": "http://www06.eyny.com/forum-160-1.html",
    "NBA籃球大聯盟": "http://www06.eyny.com/forum-236-1.html",
    "♀㊣白痴１族☆♂": "http://www06.eyny.com/forum-264-1.html",
    "ζˋ緣份網絡ˊζ": "http://www06.eyny.com/forum-282-1.html",
    "動漫新資訊": "http://www06.eyny.com/forum-479-1.html",
    "科幻/魔法類討論": "http://www06.eyny.com/forum-1842-1.html",
    "機械人討論區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=440",
    "艦隊收藏(動漫)": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3770",
    "銀魂": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1682",
    "魔法科高中的劣等生": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4239",
    "UQ HOLDER!/悠久之風(赤松健作品系列)": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1688",
    "Code Geass 反叛的魯路修": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1805",
    "魔法少女奈葉": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1803",
    "魔法禁書目錄": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1891",
    "戀愛/校園類討論": "http://www06.eyny.com/forum-1843-1.html",
    "偽戀": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3743",
    "食戟之靈": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4138",
    "政宗君的復仇": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4236",
    "不起眼女主角培育法": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4235",
    "LoveLive!": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4137",
    "出包王女": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1795",
    "京都動畫(京阿尼)系列作品": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4234",
    "Leaf &amp; Key系列作品": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1683",
    "灼眼的夏娜": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1684",
    "旋風管家": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1686",
    "華麗的挑戰 Skip Beat!": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1833",
    "D.C.~初音島~": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1838",
    "藍蘭島漂流記": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1907",
    "只有神知道的世界": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2001",
    "天降之物": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2002",
    "奇幻/冒險類討論": "http://www06.eyny.com/forum-1844-1.html",
    "火影忍者": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=433",
    "ONE PIECE 航海王(海賊王)": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=434",
    "進擊的巨人": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4237",
    "為美好的世界獻上祝福！": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4238",
    "Fate系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3832",
    "惡魔高校D×D": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3833",
    "刀劍神域": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3352",
    "加速世界": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3353",
    "約會大作戰DATE A LIVE": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4139",
    "Re:從零開始的異世界生活": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4140",
    "聖鬥士星矢": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3834",
    "死神": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=436",
    "獵人": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=441",
    "魔導少年": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1908",
    "七龍珠Z": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=471",
    "夏目友人帳": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1834",
    "驅魔少年": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1796",
    "鋼之煉金術師": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=437",
    "零之使魔": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1839",
    "狼與辛香料": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2004",
    "家庭教師 Reborn": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1678",
    "少年陰陽師": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1802",
    "推理/靈異類討論": "http://www06.eyny.com/forum-1889-1.html",
    "名偵探柯南": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=439",
    "暮蟬悲鳴時": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1798",
    "物語系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1890",
    "妖怪少爺": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1930",
    "運動/競技類討論": "http://www06.eyny.com/forum-1845-1.html",
    "新網球王子": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=438",
    "第一神拳": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1801",
    "棒球大聯盟": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1797",
    "史上最強弟子兼一": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1909",
    "王牌投手 振臂高揮": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1929",
    "動漫交流綜合討論": "http://www06.eyny.com/forum-212-1.html",
    "CLAMP系列作品": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1689",
    "歐美動漫討論區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1799",
    "義呆利Axis Power": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1910",
    "二次元偽娘討論區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1892",
    "萌系動漫討論區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3977",
    "歡樂惡搞討論區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1937",
    "燃燒吧！特攝魂討論區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1935",
    "同人創作討論區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1936",
    "萌戰討論專區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1932",
    "綜合動漫討論區": "http://www06.eyny.com/forum-3500-1.html",
    "新番動漫討論區": "http://www06.eyny.com/forum-1832-1.html",
    "動漫輕小說": "http://www06.eyny.com/forum-1681-1.html",
    "動漫討論歷史回憶區": "http://www06.eyny.com/forum-3733-1.html",
    "死亡筆記": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=478",
    "光速蒙面俠21": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1804",
    "地獄少女": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1687",
    "守護甜心": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1794",
    "涼宮春日": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1685",
    "Black★Rock Shooter": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1933",
    "結界師": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1793",
    "爆漫王": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1934",
    "學生會長是女僕": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1906",
    "今日是魔王": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1840",
    "絕望先生": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1926",
    "幸運☆星": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1800",
    "吸血鬼騎士": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1925",
    "櫻蘭高校男公關部": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1928",
    "K-ON!輕音少女": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1837",
    "虎與龍": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1841",
    "笨蛋，測驗，召喚獸": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1927",
    "黑執事": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1836",
    "薄櫻鬼": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2005",
    "惡魔奶爸": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2003",
    "聲優園地": "http://www06.eyny.com/forum-525-1.html",
    "動漫精品交流": "http://www06.eyny.com/forum-526-1.html",
    "COSPLAY交流": "http://www06.eyny.com/forum-432-1.html",
    "初音家族Vocaloid": "http://www06.eyny.com/forum-1835-1.html",
    "ACG 動漫隨意貼圖": "http://www06.eyny.com/forum-16-1.html",
    "HCG-H動漫隨意貼圖": "http://www06.eyny.com/forum-150-1.html",
    "漫畫分享版": "http://www06.eyny.com/forum-1627-1.html",
    "漫畫連載貼圖": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=481",
    "漫畫下載(上傳空間)": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1628",
    "動畫下載區(上傳空間)": "http://www06.eyny.com/forum-22-1.html",
    "高清動畫下載區(上傳空間)": "http://www06.eyny.com/forum-2035-1.html",
    "中文H漫畫貼圖": "http://www06.eyny.com/forum-349-1.html",
    "動漫音樂下載(上傳空間)": "http://www06.eyny.com/forum-207-1.html",
    "動漫音聲下載區(上傳空間)": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=4086",
    "日文H漫畫貼圖": "http://www06.eyny.com/forum-350-1.html",
    "H 漫畫下載區(上傳空間)": "http://www06.eyny.com/forum-1629-1.html",
    "英文H漫畫貼圖": "http://www06.eyny.com/forum-3208-1.html",
    "H 動畫下載區(上傳空間)": "http://www06.eyny.com/forum-431-1.html",
    "動漫套圖下載區(上傳空間)": "http://www06.eyny.com/forum-4136-1.html",
    "動漫下載求檔&amp;問題區": "http://www06.eyny.com/forum-3707-1.html",
    "搞笑貼圖區": "http://www06.eyny.com/forum-15-1.html",
    "網友自拍館": "http://www06.eyny.com/forum-14-1.html",
    "正妹美眉區": "http://www06.eyny.com/forum-17-1.html",
    "型男帥哥區": "http://www06.eyny.com/forum-520-1.html",
    "DIY作品貼圖區": "http://www06.eyny.com/forum-521-1.html",
    "網頁素材區": "http://www06.eyny.com/forum-307-1.html",
    "電腦桌布分享": "http://www06.eyny.com/forum-359-1.html",
    "BL-GL討論": "http://www06.eyny.com/forum-480-1.html",
    "BL-GL貼圖": "http://www06.eyny.com/forum-482-1.html",
    "BL-GL小說": "http://www06.eyny.com/forum-1676-1.html",
    "BL-GL衍生": "http://www06.eyny.com/forum-523-1.html",
    "BL-GL下載": "http://www06.eyny.com/forum-524-1.html",
    "BL-GL短片": "http://www06.eyny.com/forum-1807-1.html",
    "音樂新資訊": "http://www06.eyny.com/forum-1680-1.html",
    " 其他音樂討論": "http://www06.eyny.com/forum-378-1.html",
    "華語樂壇討論": "http://www06.eyny.com/forum-527-1.html",
    "日韓樂壇討論": "http://www06.eyny.com/forum-528-1.html",
    "外語樂壇討論": "http://www06.eyny.com/forum-529-1.html",
    "MP3單曲下載": "http://www06.eyny.com/forum-530-1.html",
    "MP3專輯下載": "http://www06.eyny.com/forum-203-1.html",
    "MP3華語音樂專輯": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1623",
    "MP3日韓音樂專輯": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1625",
    "MP3外語音樂專輯": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1624",
    "MP3純音樂專輯": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=380",
    "MTV和KTV下載": "http://www06.eyny.com/forum-379-1.html",
    "樂譜與樂器專區": "http://www06.eyny.com/forum-204-1.html",
    "樂譜下載區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3755",
    "歌詞分享": "http://www06.eyny.com/forum-85-1.html",
    "會員唱作區": "http://www06.eyny.com/forum-531-1.html",
    "音樂世界求檔&amp;問題區": "http://www06.eyny.com/forum-4012-1.html",
    "港台明星貼圖": "http://www06.eyny.com/forum-322-1.html",
    "日韓明星貼圖": "http://www06.eyny.com/forum-321-1.html",
    "外國明星貼圖": "http://www06.eyny.com/forum-29-1.html",
    "電視節目討論": "http://www06.eyny.com/forum-444-1.html",
    "電台節目討論": "http://www06.eyny.com/forum-443-1.html",
    "電影討論區": "http://www06.eyny.com/forum-410-1.html",
    "電視連續劇討論區": "http://www06.eyny.com/forum-327-1.html",
    "美容討論": "http://www06.eyny.com/forum-375-1.html",
    "化妝討論": "http://www06.eyny.com/forum-374-1.html",
    "減肥瘦身": "http://www06.eyny.com/forum-279-1.html",
    "女性用品": "http://www06.eyny.com/forum-1734-1.html",
    "內衣": "http://www06.eyny.com/forum-1733-1.html",
    "女人心事": "http://www06.eyny.com/forum-1731-1.html",
    "珠寶首飾": "http://www06.eyny.com/forum-1732-1.html",
    "女性健康分享": "http://www06.eyny.com/forum-1735-1.html",
    "指甲彩繪": "http://www06.eyny.com/forum-1736-1.html",
    "髮型討論": "http://www06.eyny.com/forum-377-1.html",
    "鐘錶討論": "http://www06.eyny.com/forum-451-1.html",
    "球鞋討論": "http://www06.eyny.com/forum-450-1.html",
    "潮流服飾討論": "http://www06.eyny.com/forum-201-1.html",
    "牛仔服飾": "http://www06.eyny.com/forum-1738-1.html",
    "錢包手袋": "http://www06.eyny.com/forum-1737-1.html",
    "二手衣飾交易": "http://www06.eyny.com/forum-532-1.html",
    "BT電影下載區": "http://www06.eyny.com/forum-142-1.html",
    "BT限制級電影下載": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1888",
    "BT動漫下載區": "http://www06.eyny.com/forum-609-1.html",
    "BT動漫單集下載": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=143",
    "BT動漫全集下載": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=472",
    "BT電視連續劇下載區": "http://www06.eyny.com/forum-610-1.html",
    "BT電視連續劇單集下載": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=319",
    "BT電視連續劇全集下載": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=429",
    "BT綜藝節目下載區": "http://www06.eyny.com/forum-539-1.html",
    "BT體育運動下載區": "http://www06.eyny.com/forum-540-1.html",
    "BT軟件下載區": "http://www06.eyny.com/forum-58-1.html",
    "BT遊戲下載區": "http://www06.eyny.com/forum-62-1.html",
    "BT音樂下載區": "http://www06.eyny.com/forum-141-1.html",
    "BT KTV/MTV下載": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=608",
    "BT音樂專輯下載": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=541",
    "BT H遊戲下載區": "http://www06.eyny.com/forum-1630-1.html",
    "BT H動漫下載區": "http://www06.eyny.com/forum-346-1.html",
    "BT日韓成人電影": "http://www06.eyny.com/forum-140-1.html",
    "BT歐美成人電影": "http://www06.eyny.com/forum-345-1.html",
    "BT求檔&amp;問題區": "http://www06.eyny.com/forum-538-1.html",
    "GB電影下載(GoGoBox)": "http://www06.eyny.com/forum-1613-1.html",
    "GB電視劇下載(GoGoBox)": "http://www06.eyny.com/forum-1614-1.html",
    "GB動漫下載(GoGoBox)": "http://www06.eyny.com/forum-1615-1.html",
    "GB音樂下載(GoGoBox)": "http://www06.eyny.com/forum-1620-1.html",
    "GB軟件下載(GoGoBox)": "http://www06.eyny.com/forum-1616-1.html",
    "GB遊戲下載(GoGoBox)": "http://www06.eyny.com/forum-1617-1.html",
    "GB H動漫下載(GoGoBox)": "http://www06.eyny.com/forum-1618-1.html",
    "GB H遊戲下載(GoGoBox)": "http://www06.eyny.com/forum-1621-1.html",
    "GB成人電影(GoGoBox)": "http://www06.eyny.com/forum-1619-1.html",
    "CB電影下載 (ClubBox)": "http://www06.eyny.com/forum-318-1.html",
    "CB電視劇下載 (ClubBox)": "http://www06.eyny.com/forum-1607-1.html",
    "CB成人電影 (ClubBox)": "http://www06.eyny.com/forum-353-1.html",
    "GB、CB求檔區": "http://www06.eyny.com/forum-545-1.html",
    "電影下載區(上傳空間)": "http://www06.eyny.com/forum-205-1.html",
    "限制級電影下載區(上傳空間)": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3432",
    "電視劇下載區(上傳空間)": "http://www06.eyny.com/forum-1716-1.html",
    "電視節目下載區(上傳空間)": "http://www06.eyny.com/forum-3276-1.html",
    "軟件下載區(上傳空間)": "http://www06.eyny.com/forum-18-1.html",
    "遊戲下載區(上傳空間)": "http://www06.eyny.com/forum-26-1.html",
    "GalGame遊戲下載區(上傳空間)": "http://www06.eyny.com/forum-3691-1.html",
    "H 遊戲下載區(上傳空間)": "http://www06.eyny.com/forum-48-1.html",
    "電影下載區(迅雷+百度)": "http://www06.eyny.com/forum-3520-1.html",
    "電視劇下載區(迅雷+百度)": "http://www06.eyny.com/forum-3521-1.html",
    "遊戲下載區(迅雷+百度)": "http://www06.eyny.com/forum-3523-1.html",
    "動畫下載區(迅雷+百度)": "http://www06.eyny.com/forum-3522-1.html",
    "電子書下載區": "http://www06.eyny.com/forum-1982-1.html",
    "小說下載區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=3752",
    "FLASH下載區": "http://www06.eyny.com/forum-36-1.html",
    "下載分享求檔&amp;問題區": "http://www06.eyny.com/forum-537-1.html",
    "其他短片": "http://www06.eyny.com/forum-1772-1.html",
    "搞笑短片": "http://www06.eyny.com/forum-313-1.html",
    "動漫短片": "http://www06.eyny.com/forum-1771-1.html",
    "寵物短片": "http://www06.eyny.com/forum-1755-1.html",
    "音樂短片": "http://www06.eyny.com/forum-1748-1.html",
    "寶貝BB短片": "http://www06.eyny.com/forum-1749-1.html",
    "網友自拍短片": "http://www06.eyny.com/forum-1750-1.html",
    "歌星藝人短片": "http://www06.eyny.com/forum-1754-1.html",
    "感人熱淚短片": "http://www06.eyny.com/forum-1752-1.html",
    "汽車機車短片": "http://www06.eyny.com/forum-1753-1.html",
    "體育運動短片": "http://www06.eyny.com/forum-1751-1.html",
    "電腦新資訊": "http://www06.eyny.com/forum-390-1.html",
    "電腦軟體討論": "http://www06.eyny.com/forum-53-1.html",
    "電腦軟體資訊分享": "http://www06.eyny.com/forum-546-1.html",
    "電腦硬體討論": "http://www06.eyny.com/forum-389-1.html",
    "電腦硬體資訊分享": "http://www06.eyny.com/forum-1815-1.html",
    "電腦萌化版": "http://www06.eyny.com/forum-1964-1.html",
    "電腦系統 OS 討論": "http://www06.eyny.com/forum-391-1.html",
    "WINDOWS 分享區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=548",
    "Linux": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=547",
    "WINDOWS討論": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=298",
    "MAC OS X": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=549",
    "電腦程式設計": "http://www06.eyny.com/forum-392-1.html",
    "C &amp; C++ 語言": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=550",
    "C# 語言": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=553",
    "Visual Basic 語言": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=551",
    "PHP 語言": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=295",
    "JAVA 語言": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=300",
    "CGI 語言": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=552",
    "電腦設計技術交流": "http://www06.eyny.com/forum-393-1.html",
    "網頁設計交流": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=97",
    "Flash 設計交流": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=554",
    "圖像設計及交流": "http://www06.eyny.com/forum-445-1.html",
    "各類下載工具教學": "http://www06.eyny.com/forum-394-1.html",
    "寬頻上網討論": "http://www06.eyny.com/forum-555-1.html",
    "平板電腦/iPad": "http://www06.eyny.com/forum-556-1.html",
    "數碼相機 DC": "http://www06.eyny.com/forum-557-1.html",
    "數碼攝錄機 DV": "http://www06.eyny.com/forum-558-1.html",
    "家庭影音 AV": "http://www06.eyny.com/forum-559-1.html",
    "MP3/耳機": "http://www06.eyny.com/forum-560-1.html",
    "iPod": "http://www06.eyny.com/forum-561-1.html",
    "手提電腦 NoteBook": "http://www06.eyny.com/forum-562-1.html",
    "PPC 交流": "http://www06.eyny.com/forum-563-1.html",
    "其他數碼產品": "http://www06.eyny.com/forum-95-1.html",
    "手機討論": "http://www06.eyny.com/forum-94-1.html",
    "手機選購 (2G + 3G)": "http://www06.eyny.com/forum-396-1.html",
    "手機鈴聲(非MP3)": "http://www06.eyny.com/forum-398-1.html",
    "手機鈴聲(MP3)": "http://www06.eyny.com/forum-397-1.html",
    "手機主題和桌布": "http://www06.eyny.com/forum-399-1.html",
    "手機遊戲": "http://www06.eyny.com/forum-400-1.html",
    "手機影片分享": "http://www06.eyny.com/forum-401-1.html",
    "手機成人影片分享": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1913",
    "手機軟件應用程式": "http://www06.eyny.com/forum-402-1.html",
    "二手交易": "http://www06.eyny.com/forum-211-1.html",
    "拍賣廣場": "http://www06.eyny.com/forum-376-1.html",
    "重要公告區": "http://www06.eyny.com/forum-13-1.html",
    "過時公告區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=305",
    "<b><font color=\"red\">贊助問題區</font></b>": "http://www06.eyny.com/forum-1608-1.html",
    "版主招募區": "http://www06.eyny.com/forum-43-1.html",
    "新手教學區": "http://www06.eyny.com/forum-45-1.html",
    "新手試帖區": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=174",
    "活動交流區": "http://www06.eyny.com/forum-428-1.html",
    "伊莉影片區": "http://www06.eyny.com/forum-1817-1.html",
    "伊莉部落格": "http://www06.eyny.com/forum-1813-1.html",
    "伊莉百科區": "http://www06.eyny.com/forum-1887-1.html",
    "投訴及意見": "http://www06.eyny.com/forum-44-1.html",
    "長篇小說交流園地": "http://www06.eyny.com/forum-1806-1.html",
    "出版類言情小說": "http://www06.eyny.com/forum-1677-1.html",
    "拈新閣": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=1808",
    "玄幻魔法小說": "http://www06.eyny.com/forum-1775-1.html",
    "武俠修真小說": "http://www06.eyny.com/forum-1776-1.html",
    "科幻偵探小說": "http://www06.eyny.com/forum-1774-1.html",
    "原創言情小說": "http://www06.eyny.com/forum-1773-1.html",
    "都市小說": "http://www06.eyny.com/forum-1983-1.html",
    "輕小說": "http://www06.eyny.com/forum-1777-1.html",
    "其他小說": "http://www06.eyny.com/forum-430-1.html",
    "其他運動討論": "http://www06.eyny.com/forum-1672-1.html",
    "足球討論": "http://www06.eyny.com/forum-372-1.html",
    "單車討論": "http://www06.eyny.com/forum-1719-1.html",
    "籃球討論": "http://www06.eyny.com/forum-365-1.html",
    "田徑討論": "http://www06.eyny.com/forum-1720-1.html",
    "棒球討論": "http://www06.eyny.com/forum-105-1.html",
    "羽毛球討論": "http://www06.eyny.com/forum-366-1.html",
    "乒乓球討論": "http://www06.eyny.com/forum-452-1.html",
    "撞球(桌球)討論": "http://www06.eyny.com/forum-566-1.html",
    "健身運動討論": "http://www06.eyny.com/forum-371-1.html",
    "武術討論": "http://www06.eyny.com/forum-367-1.html",
    "中國武術討論": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=368",
    "日韓武術討論": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=369",
    "格鬥擂台討論": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=370",
    "爬山及遠足討論": "http://www06.eyny.com/forum-373-1.html",
    "瑜伽討論": "http://www06.eyny.com/forum-567-1.html",
    "排球討論": "http://www06.eyny.com/forum-568-1.html",
    "網球/壁球討論": "http://www06.eyny.com/forum-569-1.html",
    "高爾夫球討論": "http://www06.eyny.com/forum-570-1.html",
    "職業摔角討論": "http://www06.eyny.com/forum-564-1.html",
    "潛水討論": "http://www06.eyny.com/forum-565-1.html",
    "時事討論": "http://www06.eyny.com/forum-1724-1.html",
    "明星新聞討論": "http://www06.eyny.com/forum-412-1.html",
    "有趣新聞": "http://www06.eyny.com/forum-1760-1.html",
    "企業家管理交流": "http://www06.eyny.com/forum-447-1.html",
    "金融財經、投資交流": "http://www06.eyny.com/forum-449-1.html",
    "房地產討論": "http://www06.eyny.com/forum-571-1.html",
    "股票討論": "http://www06.eyny.com/forum-573-1.html",
    "基金保險": "http://www06.eyny.com/forum-1762-1.html",
    "外幣投資": "http://www06.eyny.com/forum-1761-1.html",
    "租屋資訊": "http://www06.eyny.com/forum-1764-1.html",
    "環境保護問題探討": "http://www06.eyny.com/forum-1770-1.html",
    "食物衛生及用品安全": "http://www06.eyny.com/forum-1769-1.html",
    "軍事討論": "http://www06.eyny.com/forum-572-1.html",
    "軍事貼圖": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=360",
    "上班樂與怒": "http://www06.eyny.com/forum-303-1.html",
    "工作薪酬討論": "http://www06.eyny.com/forum-467-1.html",
    "創業討論區": "http://www06.eyny.com/forum-446-1.html",
    "網路賺錢": "http://www06.eyny.com/forum-574-1.html",
    "各行各業": "http://www06.eyny.com/forum-575-1.html",
    "求職者交流": "http://www06.eyny.com/forum-1765-1.html",
    "兼職工讀交流": "http://www06.eyny.com/forum-1767-1.html",
    "人力銀行(提供職位資訊)": "http://www06.eyny.com/forum-1768-1.html",
    "兩性討論": "http://www06.eyny.com/forum-156-1.html",
    "夜遊討論": "http://www06.eyny.com/forum-335-1.html",
    "成人交友": "http://www06.eyny.com/forum-336-1.html",
    "成人貼圖": "http://www06.eyny.com/forum-577-1.html",
    "日韓美女": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=32",
    "歐美少女": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=338",
    "本地美女": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=339",
    "明星走光": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=340",
    "成人電影(上傳空間)": "http://www06.eyny.com/forum-576-1.html",
    "本土電影(上傳空間)": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=348",
    "日韓電影(上傳空間)": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=2",
    "歐美電影(上傳空間)": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=347",
    "成人小說": "http://www06.eyny.com/forum-6-1.html",
    "改編系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=344",
    "亂倫系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=341",
    "誘騙系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=342",
    "強暴系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=343",
    "變身系列": "http://www06.eyny.com/forum.php?mod=forumdisplay&fid=475",
    "足球投注": "http://www06.eyny.com/forum-351-1.html",
    "虛擬足球投注站": "http://www06.eyny.com/forum-606-1.html",
    "香港賽馬": "http://www06.eyny.com/forum-354-1.html",
    "賭場討論": "http://www06.eyny.com/forum-355-1.html",
    "麻雀耍樂": "http://www06.eyny.com/forum-357-1.html",
    "撲克交流": "http://www06.eyny.com/forum-356-1.html"
}

$ = jQuery.noConflict(true);
document.cookie = 'djAX_e8d7_agree=206;path=/;domain=.eyny.com'; // dealing r18 authentication

$('#hd').siblings()[2].innerHTML = "" // get rid of announcement since it may contain link to specific forum

if(debug == true){
    container = {}
    $('[href]').filter(function(){
        return this.href.match(/forum((-.)|(\.php\?((view=all)|(mod=forumdisplay\&fid))))/)
    }).each(function(index, value){
        container[value.innerHTML] = value.href;
    })
    console.log(JSON.stringify(container, null, 4));
}
else{

    // Don't touch this, this is my development flags
    version = 1

    if(version == 0){
        var forumId = []
        $.ajax({
            url : `http://${location.hostname}/forum.php?view=all`,
            async: false,
            //headers: { 'Access-Control-Allow-Origin': '*' },
            method : "get"
        }).done(function(body){
            $(body).find('[href]').filter(function(){
                return this.href.match(/forum((-.)|(\.php\?view=all))/)
            }).each(function(index, value){
                forumId.push(value.href);
            })
        })

         $('[href]').filter(function(){
             return this.href.match(/forum((-.)|(\.php\?((view=all)|(mod=forumdisplay\&fid))))/)
         }).each(function(index, value){
             if(value == 'forum.php?view=all'){
                 $(this).attr('href',`http://yrwww${Math.floor(Math.random() * 1000 + 1000)}.eyny.com/forum.php?mod=forumdisplay&fid=${forumId[index]}&filter=author&orderby=dateline`)
             }
             else{
                 if(value.href.match(/forum\.php\?mod=forumdisplay&fid./)){
                     var fid = value.href.substring(value.href.lastIndexOf('=')+1,value.href.length);
                     if(exclude.indexOf(fid) == -1)
                         $(this).attr('href',`http://yrwww${Math.floor(Math.random() * 1000 + 1000)}.eyny.com/forum.php?mod=forumdisplay&fid=${fid}&filter=author&orderby=dateline`)
                 }
                 else{
                     var fid = value.href.substring( value.href.lastIndexOf('forum-')+6,value.href.lastIndexOf('-'))
                     if(exclude.indexOf(fid) == -1)
                         $(this).attr('href',`http://yrwww${Math.floor(Math.random() * 1000 + 1000)}.eyny.com/forum.php?mod=forumdisplay&fid=${fid}&filter=author&orderby=dateline`)
                 }
             }
         })

        $("span[id*='category']").each(function(){
            $(this).prev().append('<a class="yrExpand" href="javascript: void(0);">Ep</a>')
        })

        $('.yrExpand').click(function(event){
            if($(event.target).parent().next().css('display') == 'none')
                $(event.target).parent().next().css('display','inline');
            else
                $(event.target).parent().next().css('display','none');
        })
    }
    else{
         $('[href]').filter(function(){
             return this.href.match(/forum((-.)|(\.php\?((view=all)|(mod=forumdisplay\&fid))))/)
         }).each(function(index, value){

             if(value.href.indexOf('forum.php?view=all') != -1){
                 index = value.innerHTML;

                 if(typeof fourmIDStatic[index] == "undefined"){
                     // 子論壇上面的 banner，例如：動漫交流 (圖片)
                     // href format: http://yrwww1542.eyny.com/forum.php?gid=206
                     return;
                 }

                 fid = fourmIDStatic[index].substring(fourmIDStatic[index].indexOf('forum-') + 'forum-'.length, fourmIDStatic[index].lastIndexOf('-'))
                 $(this).attr('href',`http://yrwww${Math.floor(Math.random() * 1000 + 1000)}.eyny.com/forum.php?mod=forumdisplay&fid=${fid}&filter=author&orderby=dateline`)
             }
             else{
                 
                 if(value.href.match(/forum\.php\?mod=forumdisplay&fid./)){
                     var fid = value.href.substring(value.href.lastIndexOf('=')+1,value.href.length);
                     if(exclude.indexOf(fid) == -1)
                         $(this).attr('href',`http://yrwww${Math.floor(Math.random() * 1000 + 1000)}.eyny.com/forum.php?mod=forumdisplay&fid=${fid}&filter=author&orderby=dateline`)
                 }
                 else{
                     var fid = value.href.substring( value.href.lastIndexOf('forum-')+6,value.href.lastIndexOf('-'))
                     if(exclude.indexOf(fid) == -1)
                         $(this).attr('href',`http://yrwww${Math.floor(Math.random() * 1000 + 1000)}.eyny.com/forum.php?mod=forumdisplay&fid=${fid}&filter=author&orderby=dateline`)
                 }
             }
         })
    }
}